In [1]:
import scipy
from scipy import stats
import numpy as np

In [8]:
matrix = np.array([[8,0,3,4,6],[5,6,1,8,9],[8,0,5,10,9]])
novoUser = [8,0,2,3,0]
nao_assistidos = [0,1,0,0,1]
print(matrix)
nomeFilmes = ['Round 6', 'A Invocação do Mal,', '9 Desconhecidos','You', 'La casa de papel']

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  5 10  9]]


In [9]:
similarity = [0] * 3
print(matrix[0],[0])
print(matrix[1],[0])
print(matrix[1,:])

for i in range (0,3):
  temp = matrix[i,:]

  print(i, temp)

  tempUser = [t for n,t in zip(novoUser,temp) if n != 0]
  tempNovoUser = [n for n in novoUser if n != 0]

  print('user:', i)
  print(tempUser, tempNovoUser)

  similarity[i] = scipy.stats.pearsonr(tempUser, tempNovoUser)[0]

print()
print(similarity)


[8 0 3 4 6] [0]
[5 6 1 8 9] [0]
[5 6 1 8 9]
0 [8 0 3 4 6]
user: 0
[np.int64(8), np.int64(3), np.int64(4)] [8, 2, 3]
1 [5 6 1 8 9]
user: 1
[np.int64(5), np.int64(1), np.int64(8)] [8, 2, 3]
2 [ 8  0  5 10  9]
user: 2
[np.int64(8), np.int64(5), np.int64(10)] [8, 2, 3]

[np.float64(0.9994237971287664), np.float64(0.23621543814299698), np.float64(0.267827834114857)]


In [10]:
nota_peso = np.zeros((3,5))

for nUser in range(3):
  for nFilme in range(5):
    print('nota_peso[',nUser, '][',nFilme, '] = , nao_assistidos[',nFilme, '], * ,matrix[',nUser,'][',nFilme, '], * similarity[',nUser,']')
    print('nota_peso[',nUser, '][',nFilme, '] = ', nao_assistidos[nFilme], ' * ' ,matrix[nUser][nFilme], ' * ', similarity[nUser])
    nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

print(nota_peso)


nota_peso[ 0 ][ 0 ] = , nao_assistidos[ 0 ], * ,matrix[ 0 ][ 0 ], * similarity[ 0 ]
nota_peso[ 0 ][ 0 ] =  0  *  8  *  0.9994237971287664
nota_peso[ 0 ][ 1 ] = , nao_assistidos[ 1 ], * ,matrix[ 0 ][ 1 ], * similarity[ 0 ]
nota_peso[ 0 ][ 1 ] =  1  *  0  *  0.9994237971287664
nota_peso[ 0 ][ 2 ] = , nao_assistidos[ 2 ], * ,matrix[ 0 ][ 2 ], * similarity[ 0 ]
nota_peso[ 0 ][ 2 ] =  0  *  3  *  0.9994237971287664
nota_peso[ 0 ][ 3 ] = , nao_assistidos[ 3 ], * ,matrix[ 0 ][ 3 ], * similarity[ 0 ]
nota_peso[ 0 ][ 3 ] =  0  *  4  *  0.9994237971287664
nota_peso[ 0 ][ 4 ] = , nao_assistidos[ 4 ], * ,matrix[ 0 ][ 4 ], * similarity[ 0 ]
nota_peso[ 0 ][ 4 ] =  1  *  6  *  0.9994237971287664
nota_peso[ 1 ][ 0 ] = , nao_assistidos[ 0 ], * ,matrix[ 1 ][ 0 ], * similarity[ 1 ]
nota_peso[ 1 ][ 0 ] =  0  *  5  *  0.23621543814299698
nota_peso[ 1 ][ 1 ] = , nao_assistidos[ 1 ], * ,matrix[ 1 ][ 1 ], * similarity[ 1 ]
nota_peso[ 1 ][ 1 ] =  1  *  6  *  0.23621543814299698
nota_peso[ 1 ][ 2 ] = , nao_assi

In [11]:
notas_acumuladas = np.sum(nota_peso.T,axis=1)
print(notas_acumuladas)

[ 0.          1.41729263  0.          0.         10.53293223]


In [12]:
temp_peso = nota_peso
temp_peso[nota_peso > 0] = 1
print(temp_peso)
temp_similaridade = np.zeros((3,5))
for nUser in range(3):
  for nFilme in range(5):
    temp_similaridade[nUser][nFilme] = temp_peso[nUser][nFilme] * similarity[nUser]

print(temp_similaridade)

similaridade_acumulada = np.sum(temp_similaridade.T,axis=1)
print(similaridade_acumulada)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
[[0.         0.         0.         0.         0.9994238 ]
 [0.         0.23621544 0.         0.         0.23621544]
 [0.         0.         0.         0.         0.26782783]]
[0.         0.23621544 0.         0.         1.50346707]


In [13]:
nota_final =[0] * 5
#agora a normalização para cada filme com nota acumulada, eu normalizo pela soma dos pesos (similaridade)
for nFilme in range(5):
  if(similaridade_acumulada[nFilme] > 0):
    nota_final[nFilme] =  notas_acumuladas[nFilme] / similaridade_acumulada[nFilme]
  else:
    nota_final[nFilme] = 0

print(nota_final)

[0, np.float64(6.0), 0, 0, np.float64(7.005761847108814)]


In [14]:
nAssistidos = sum(nao_assistidos)

notasOrdenadasIndex = sorted(range(len(nota_final)),key=nota_final.__getitem__)[::-1][0:nAssistidos]
print(notasOrdenadasIndex)

for i in notasOrdenadasIndex:
  print(nomeFilmes[i], 'nota: ', nota_final[i])

[4, 1]
La casa de papel nota:  7.005761847108814
A Invocação do Mal, nota:  6.0
